name: "Upgrade FluxCD 2 in cluster directory"
description: "Upgrade FluxCD 2 in cluster directory"
inputs:
  directory:
    description: "Cluster directory"
    required: true
  file:
    description: "FluxCD 2 flux-system/gotk-components.yaml file"
    default: "flux-system/gotk-components.yaml"
  token:
    description: "Workflow token"
    default: ${{ github.token }}
  labels:
    description: "Pull request labels"
    default: |
      flux/upgrade
runs:
  using: "composite"
  steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2

      - name: Use latest FluxCD client
        uses: fluxcd/flux2/action@main

      - name: Upgrade FLuxCD in cluster
        shell: bash
        id: upgrade
        run: |
          UGLY_FLUX_VERSION="$(flux -v)"
          PRETTY_FLUX_VERSION="$(echo ${UGLY_FLUX_VERSION} | cut -s -d ' ' -f 3)"
          FLUX_VERSION="v${PRETTY_FLUX_VERSION}"
          flux install --version="${FLUX_VERSION}" \
            --components-extra=image-reflector-controller,image-automation-controller \
            --export > ./${{ inputs.directory }}/${{ inputs.file }}
          echo "flux_version=$FLUX_VERSION" >> $GITHUB_OUTPUT

      - name: Create PR
        uses: peter-evans/create-pull-request@v7.0.8
        with:
          signoff: true
          delete-branch: true
          committer: "fluxcdbot <fluxcdbot@users.noreply.github.com>"
          author: "fluxcdbot <fluxcdbot@users.noreply.github.com>"
          draft: false
          labels: |
            ${{ inputs.labels }}
          token: ${{ inputs.token }}
          branch: "${{ inputs.directory }}/${{ inputs.file }}/${{ steps.upgrade.outputs.flux_version }}"
          title: "chore(deps): upgrade [${{ inputs.directory }}] flux components to ${{ steps.upgrade.outputs.flux_version }}"
          commit-message: "chore(deps): upgrade [${{ inputs.directory }}] flux components to ${{ steps.upgrade.outputs.flux_version }}"
          body: |
            Release notes: https://github.com/fluxcd/flux2/releases/tag/${{ steps.upgrade.outputs.flux_version }}
branding:
  icon: folder
  color: white
